{

"header" : {
  "navbar" : {
    "UPLOAD" : "Upload",
    "new" : {
    	"NEW" : "New",
    	"PROJECT" : "Projects",
    	"TASK" : "Task",
    	"USER" : "User",
    	"EMAIL" : "Email"
    },
    "NOTIFICATIONS" : "Notifications",
    "SETTING": "Setting",
    "THEMESETTING": "Theme Setting",
    "HELP": "Help",
    "LOGOUT": "Logout"
  }
},

"product" : {
    "CORPORATION": "The 32nd institute of china electronics technology group corporation",
    "DATE" : "2015"
},

"aside" : {
  "nav" : {
    "HEADER" : "Navigation",
    "DASHBOARD" : "Dashboard",
    "ATTACK_ANALYSE" : "Attack Analysis",
    "FLOW_ANALYSE" : "Traffic Analysis",
    "CONFIGURATION" : "Configuration",
    "USER_MANAGEMENT" : "User Management",
    "AUTH_MANAGEMENT" : "Auth Management",
    "SYSTEM_CONFIG" : "System",
    "CALENDAR" : "Calendar",
    "EMAIL" : "Email",
    "WIDGETS" : "Widgets",
    "POLICY_MANAGEMENT" : "Policy",
    "LOG" : "log",
    "FLOW" : "flow",
    "components" : {
      "COMPONENTS" : "Components",
      "COMMON_COMPONENTS": "Common Components",
      "ui_kits" : {
    	 "UI_KITS" : "UI Kits",
    	 "BUTTONS" : "Buttons",
    	 "ICONS" : "Icons",
    	 "GRID" : "Grid",
    	 "BOOTSTRAP" : "Bootstrap",
    	 "SORTABLE" : "Sortable",
    	 "PORTLET" : "Portlet",
    	 "TIMELINE" : "Timeline",
    	 "VECTOR_MAP" : "Vector Map"
    	},
      "FILE_UPLOAD": "File Upload",
      "FILE_DOWNLOAD": "File Download",
      "table" : {
        "TABLE" : "Table",
        "TABLE_PAGE" : "Table and Page",
        "TABLE_STATIC" : "Table static",
        "DATATABLE" : "Datatable",
        "FOOTABLE" : "Footable"
      },
      "form" : {
        "FORM" : "Form",
        "FORM_ELEMENTS" : "Form elements",
        "FORM_VALIDATION" : "Form validation",
        "FORM_WIZARD" : "Form wizard"
      },
      "CHART" : "Chart",
      "pages" : {
        "PAGES" : "Pages",
        "PROFILE" : "Profile",
        "POST" : "Post",
        "SEARCH" : "Search",
        "INVOICE" : "Invoice",
        "LOCK_SCREEN" : "Lock screen",
        "SIGNIN" : "Signin",
        "SIGNUP" : "Signup",
        "FORGOT_PASSWORD" : "Forgot password",
        "404" : "404"
      }
    },
    "your_stuff" : {
      "YOUR_STUFF": "Your Stuff",
      "PROFILE" : "Profile",
      "DOCUMENTS" : "Documents"
    },
    "attackanalyse": {
        "ATTACK_TOTAL": "Attack Profile",
        "ATTACK_LOCATION": "Attack Distribution"
    },
    "flowanalyse": {
        "FLOW_TOTAL": "Flow Overview",
        "FLOW_CONTRAST": "Flow Contrast"
    },
    "policies": {
        "CONTROLLER":"Detection device",
        "NET_NODE": "Network node",
        "PROTECT_OBJECT": "Protect object",
        "CLEAN_DEV":"Clean device"
    },
    "systems": {
        "ADMINISTRATOR": "Administrator configure",
        "BACKUP_RESTORE": "Backup & restore"
    },
    "logs": {
        "SYSLOG": "System log",
        "OPLOG": "Operation log",
        "DEVLOG": "CleanDev log"
    },
    "flows": {
        "HISTORY_FLOW": "History flow",
        "FLOW_BASELINE": "Flow baseline"
    }
  },
  "MILESTONE" : "Milestone",
  "RELEASE" : "Release"
},
"settings": {
	"SETTINGS": "Settings",
	"FIXED_HEADER": "Fixed header",
	"FIXED_ASIDE": "Fixed aside",
	"FOLDED_ASIDE": "Folded aside",
	"DOCK_ASIDE": "Dock aside",
	"BOXED_LAYOUT": "Boxed layout",
    "RESET_SETTINGS": "Reset"
},
"usermanage": {
	"USERNAME": "UserName",
    "USERNAME_EMPTY": "Username can't be empty",
    "USERNAME_SAME": "This username is exist,please change it",
	"NICKNAME": "NickName",
	"NICKNAME_EMPTY": "Nickname can't be empty",
	"CREATETIME": "Create Time",
	"ROLES": "Roles",
	"ROLE_EMPTY": "Role can't be empty",
	"PASSWORD": "Password",
	"RESETPW": "Reset Password",
	"MODIFYPW": "Modify Password",
	"NOMODIFYPW": "Do not Modify Password",
	"NEWPASSWORD": "Input New Password",
	"CHECKPW": "Check Password",
    "CLEANDEV":"Clean dev"
},
"commonword": {
	"SAVE": "Save",
	"CANCEL": "Cancel",
	"DELETE": "Delete",
	"BACK": "Back",
	"ADD": "Add",
	"LOADING": "Loading",
	"NODATA": "data is not found",
	"EDIT": "edit",
	"PASSWORDWRONG": "Number of Password must be big than six",
	"CHECKWRONG": "Check Password Wrong, Input the Password again",
    "SAVE_FAIL": "Save configuration failed",
    "GET_FAIL": "Get data failed"
},
"overView": {
        "NORMAL": "Number of normal",
        "EXCEPTION": "Number of exception",
        "ATTACK": "Number of attack",
        "DEFENSE": "Number of defense",
        "NUMBER_RATIO": "Ratio of Number",
        "PROTOCOL_RATIO": "Ratio of protocol",
        "ATTACK_EVENT": "attack and defense event",
        "EVENT_TYPE": "event type",
        "ATTACK_EVENT_ATTACKED": "attacked",
        "ATTACK_EVENT_START_DEFENSE": "start defense",
        "ATTACK_EVENT_STOP_DEFENSE": "stop defense",
        "START_LIMIT": "start limit",
        "START_GUIDE": "start guide",
        "STOP_LIMIT": "stop limit",
        "STOP_GUIDE": "stop guide",
        "NORMAL_TIME": "speed normal times", 
        "ABNORMAL_TIME": "speed abnormal times",
        "ATTACK_TIME": "attack times",
        "DETECT_TYPE": "detect type",
        "EVENT_TIME": "time",
        "EVENT_PO": "po",
        "EVENT_PROTOCOL": "protocol",
        "EVENT_RATE": "attack rate",
        "EVENT_DEFENSE": "defense action",
        "ATTACK_DETAIL_LIST": "attack detailed list",
        "RECOVER_NUMBER": "Number of recover"
},

"dataOverView": {
    "FLOW_CONTRAST":"Flow Contrast",
    "INPUT_FLOW":"input flow",
    "OUTPUT_FLOW":"output flow",
    "ATTACK_FLOW":"attack flow",
    "INPUT_FLOW_DISTRIBUTION":"Input-Flow Distribution",
    "PROTOCOL_TCP":"TCP",
    "PROTOCOL_UDP":"UDP",
    "PROTOCOL_ICMP":"ICMP",
    "PROTOCOL_OTHER":"OTHER",
    "PROTECT_OBJECT_FLOW_TOP10":"Protect Object Flow Top 10",
    "IP_FLOW_TOP10":"Attack IP Flow Top 10",
    "TIME":"time",
    "TRAFFIC":"traffic(B/s)",
    "PO":"protect object",
    "IP":"IP"
},

"attackView":{
    "ATTACK_NUM": "Number of attack",
    "DEFENSE_NUM": "Number of defense",
    "CLEAN_TRAFFIC":"Clean traffics",
    "ATTACK_SRC_NUM":"Number of attack src",
    "DDOS_ATTACK_TYPE":"The distribution of ddos attack",
    "CC_ATTACK":"CC",
    "SYN_FLOOD":"SYN FLOOD",
    "ACK_FLOOD":"ACK FLOOD",
    "SYN_ACK_FLOOD":"SYN-ACK FLOOD",
    "FIN_RST_FLOOD":"FIN-RST FLOOD",
    "UDP_FLOOD":"UDP FLOOD",
    "ICMP_FLOOD":"ICMP FLOOD",
    "DNS_FLOOD":"DNS FLOOD",
    "ATTACK_DETAIL":"attack detail",
    "PO_IP":"PO IP",
    "PO_NAME":"PO Name",
    "ABNORMAL_STARTING_TIME":"The starting time of abnormal",
    "ATTACK_STARTING_TIME":"The starting time of attack",
    "END_TIME":"End time",
    "DURATION_TIME":"Duration time",
    "STATUS":"Attack Status",
    "TYPE":"Attack Type",
    "ATTACK_SRC_IP":"Attack src ip",
    "ATTACK_TYPE":"Attack type",
    "ATTACK_PKT_NUM":"Attack packets",
    "ATTACK_BYTES_NUM":"Attack bytes",
    "ATTACK_PEAK":"Attack peak",
    "ATTACK_FLOW_VALUE":"Value of attack flow",
    "FLOW_THRESHOLD":"Flow threshold",
    "DDOS_DEFENSE_WEEK_TREND":"DDOS Defense Weekly Trend",
    "DDOS_DEFENSE_24HOURS_TREND":"DDOS Defense 24 hours Trend",
    "DDOS_DEFENSE_NUM":"the number of ddos defense",
    "MAX_ATTACK_FLOW":"the maximum of attack flow(GB/s)"
},

"flowDisplay": {
    "SELECT_PO":"Please select the object of protection",
    "SELECT_PROTOCOL":"Please select a protocol",
    "SELECT_TIME":"Please select time slot",
    "FLOWTIME":"Time",
    "INPUT":"Input traffic(B/s)",
    "OUTPUT":"Output traffic(B/s)",
    "ATTACK":"Attack traffic(B/s)",
    "QUERY":"Query",
    "DISPLAYSHOW":"Traffic display",
    "HOUR_CHART":"One hour flow chart",
    "WEEK_CHART":"One week flow chart",
    "DAY_CHART":"One day flow chart",
    "MONTH_CHART":"Month flow chart",
    "YEAR_CHART":"Year flow chart",
    "BASELINE_CHART":"Flow baseline chart",
    "BASELINE_SPEED" : "Baseline speed",
    "BASELINE_LEARNING" : "Base is learning",
    "RROTOCOL_DIST":"Protocol distribution graph",
    "RROTOCOL":"Protocol",
    "RATE":"Rate(B/s)",
    "PERCENT":"Percent",
    "ONE_HOUR" : "One hour",
    "ONE_DAY" : "1 day",
    "ONE_WEEK" : "1 week",
    "ONE_MONTH" : "1 month",
    "ONE_YEAR" : "1 year",
    "FLOW_CHART" : "Flow chart",
    "SPEED" : "Speed",
    "TIME" : "time",
    "HOUR" : "hour",
    "MON" : "Monday",
    "TUE" : "Tuesday",
    "WED" : "Wednesday",
    "THURS" : "Thursday",
    "FRI" : "Friday",
    "SAT" : "Saturday",
    "SUN" : "Sunday"

},
"controller": {
    "TYPE": "Detection type",
    "HOST": "Detection host",
    "PORT": "port",
    "USER": "user",
    "PASSWORD": "password",
    "INTERVAL": "Check interval(sec.)",
    "EXCEPTION_COUNT": "Exception count threshold",
    "EXCEPTION_PER": "Exception flow rate percentage",
    "RECOVER_COUNT": "Recover count threshold",
    "SAVE_FAIL": "Save detection device configuration fail",
    "GET_FAIL": "Get detection device configuration fail",
    "ADDR_EMPTY": "Address can't be empty",
    "EXISTED": "The detection device is already existing",
    "PORT_EMPTY": "Port can't be empty",
    "PORT_RANGE": "Port range must be between 1 and 65535",
    "USER_EMPTY": "User name can't be empty",
    "PASSWORD_EMPTY": "Password can't be empty",
    "TIME_INTERVAL_EMPTY": "Interval time can't be empty",
    "TIME_INTERVAL_RANGE": "Interval time must be between 5 and 600",
    "EXCEPTION_COUNT_EMPTY": "Exception count threshold can't be empty",
    "EXCEPTION_COUNT_RANGE": "Exception count threshold must be between 0 and 100",
    "EXCEPTION_PER_EMPTY": "Exception flow rate percentage can't be empty",
    "EXCEPTION_PER_RANGE": "Exception flow rate percentage must be between 0 and 1000",
    "RECOVER_COUNT_EMPTY": "Recover count threshold can't be empty",
    "RECOVER_COUNT_RANGE": "Recover count threshold must be between 0 and 100"
},
"netnode": {
    "NAME": "NetNode name",
    "ID": "NetNode id",
    "CONTROLLER_ID": "Controller id",
    "NAME_EXIST": "Netnode name already exists",
    "NAME_EMPTY": "Netnode name can't be empty",
    "CONTROLLER_ID_EMPTY": "Controller id can't be empty",
    "ID_EMPTY": "Netnode id can't be empty",
    "SAVE_FAIL": "Save netnode configuration failed",
    "GET_FAIL": "Get netnode configuration failed"
},
"backup": {
    "BACKUPDB": "Backup",
    "BACKUPANDDOWNLOAD": "backup",
    "SELECTBACKUPFILE": "Restore",
    "SELECTFILE": "Select file",
    "UPLOADRESTORE": "upload",
    "GET_FAIL": "Get configuration failed",
    "BACKUPSUCCESS": "Backup configuration successfully!",
    "BACKUPFAIL": "Backup configuration failed!",
    "RESTORESUCCESS": "Restore configuration successfully!",
    "RESTOREFAIL": "Restore configuration failed!"
},
"po": {
    "NAME": "Name",
    "CONNECT_MODE":"Connect mode",
    "BYPASS_MODE":"Bypass mode",
    "TADEM_MODE":"Tadem mode",
    "CLEAN_DEV": "Clean device",
    "IFACE_PORT": "Port",
    "EXIST_DETECTOR": "Exist detector",
    "REINJECTION_PORT": "Reinjection interface",
    "INPUT_PORT": "Input interface",
    "OUTPUT_PORT": "Output interface",
    "CLEANDEV_OUTPORT": "Cleandev out-port",
    "CLEANDEV_INPORT": "Cleandev in-port",
    "PROTECT_NETWORK": "Protect network",
    "DEFENSE_TYPE": "Defense type",
    "GUIDE_PORT": "Guide interface",
    "CONNECT_SWITCH": "Connect detection device",
    "CONNECT_CLEANDEV": "Connect cleandev",
    "TENANT": "Tenant",
    "SHOW_TENANT": "Tenant",
    "SELECT_TENANT":"Select Tenant",
    "PROTOCOL": "Protocol",
    "FLOW_THRESHOLD": "Flow threshold",
    "AUTO_LEARN": "Auto-learn flow threshold",
    "FIXED_FLOW_THRESHOLD": "Fixed flow threshold",
    "NAME_EXIST": "Name already exists,please change one",
    "NAME_EMPTY": "Name can't be empty",
    "INPUT_PORT_EMPTY": "Input interface can't be empty",
    "OUTPUT_PORT_EMPTY": "Output interface can't be empty",
    "PROTECT_NETWORK_EMPTY": "protect network input is not correct, correct format is like 10.10.10.10/32",
    "NETWORK_EXIST": "PO network already exists",
    "PROTECT_NETWORK_NULL": "protect network can not be empty",
    "DEFENSE_TYPE_EMPTY": "Defense type can't be empty",
    "GUIDE_PORT_EMPTY": "Guide interface can't be empty",
    "REINJECTION_PORT_EMPTY": "Reinjection interface can't be empty",
    "CONNECT_SWITCH_EMPTY": "Connect detection device can't be empty",
    "PROTOCOL_EMPTY": "Please select one protocol type at least",
    "FLOW_THRESHOLD_TYPE_EMPTY": "Flow threshold can't be empty",
    "IPOPTION_THRESHOLD": "IP Option flood threshold",
    "IPOPTION_THRESHOLD_EMPTY": "IP Option flood threshold can't be empty",
    "ICMP_REDIRECT":"ICMP redirect",
    "PPS_EMPTY": "pps can't be empty",
    "KBPS_EMPTY": "KB/s can't be empty",
    "PPS_TYPE": "pps must be positive integer",
    "KBPS_TYPE": "KB/s must be Positive integer",
    "SAVE_FAIL": "Save PO configuration failed",
    "THRESHOLD_RANGE": "Threshold range must be between 1 and 9999999999",
    "GET_FAIL": "Get PO configuration failed"
},
"cleandev": {
    "CLEANDEV_IP": "Clean device ip",
    "CLEAN_DIRECTION": "Clean direction",
    "CLEAN_DIRECTION_EMPTY": "Clean direction can't be empty",
    "UNIDERECTION": "Uni-direction",
    "BIDIRECTIONAL": "Bi-direction",
    "TCP_FIRST_SYN":"TCP first packet discard",
    "CHECK_INTERVAL": "Check interval",
    "CHECK_INTERVAL_EMPTY": "Check interval can't be empty",
    "TCP_FLOOD_THRESHOLD": "TCP flood threshold",
    "TCP_FLOOD_THRESHOLD_EMPTY": "TCP flood threshold can't be empty",
    "TCP_SYNACK_CLEAN": "TCP syn+ack threshold",
    "TCP_SYNACK_CLEAN_EMPTY": "TCP syn+ack threshold can't be empty",
    "TCP_SYN_CLEAN": "TCP syn threshold",
    "TCP_SYN_CLEAN_EMPTY": "TCP syn threshold can't be empty",

    "TCP_ABNORMAL_CLEAN": "TCP abnormal package clean",
    "TCP_ABNORMAL_CLEAN_EMPTY": "TCP abnormal threshold can't be empty",
    "UDP_THRESHOLD": "Udp threshold",
    "UDP_THRESHOLD_EMPTY": "UDP threshold can't be empty",
    "ICMP_THRESHOLD": "Icmp threshold",
    "ICMP_THRESHOLD_EMPTY": "ICMP threshold threshold can't be empty",
    "ICMP_ABNORMAL_CLEAN": "Icmp abnormal package clean",
    "ICMP_ABNORMAL_CLEAN_EMPTY": "Icmp abnorma can't be empty",
    "HTTP_THRESHOLD": "Http flood threshold",
    "HTTP_THRESHOLD_EMPTY": "Http flood threshold can't be empty",
    "HTTP_REQUEST_THRESHOLD": "Http request threshold",
    "HTTP_REQUEST_THRESHOLD_EMPTY": "Http request threshold can't be empty",
    "HTTP_HEADER_THRESHOLD": "Http header slow threshold",
    "HTTP_HEADER_THRESHOLD_EMPTY": "Http header slow threshold can't be empty",
    "HTTP_POST_THRESHOLD": "Http post threshold",
    "HTTP_POST_THRESHOLD_EMPTY": "Http post threshold can't be empty",
    "HTTP_PORT": "Http port",
    "HTTP_PORT_EMPTY": "Http port can't be empty",
    "HTTP_SRC_AUTH":"Http source authentication",
    "HTTPS_FLOOD_THRESHOLD": "Https flood threshold",
    "HTTPS_FLOOD_THRESHOLD_EMPTY": "Https flood threshold can't be empty",
    "HTTPS_REQUEST_THRESHOLD": "Https request threshold",
    "HTTPS_REQUEST_THRESHOLD_EMPTY": "Https request threshold can't be empty",
    "HTTPS_THC_THRESHOLD": "Https thc threshold",
    "HTTPS_THC_THRESHOLD_EMPTY": "Https thc threshold can't be empty",
    "HTTPS_PORT": "Https port",
    "HTTPS_PORT_EMPTY": "Https port can't be empty",
    "DNS_REQ_THRESHOLD": "DNS request threshold",
    "DNS_REQ_THRESHOLD_EMPTY": "DNS request threshold can't be empty",
    "DNS_REP_THRESHOLD": "DNS reply threshold",
    "DNS_REP_THRESHOLD_EMPTY": "DNS reply threshold can't be empty",
    "DNS_PORT": "DNS port",
    "DNS_PORT_EMPTY": "DNS port can't be empty",
    "DNS_ABNORMAL_CLEAN": "DNS abnormal package clean",
    "DNS_ABNORMAL_CLEAN_EMPTY": "DNS abnormal package clean can't be empty",

    "NTP_PORT": "NTP port",
    "NTP_PORT_EMPTY": "NTP port can't be empty",
    "NTP_THRESHOLD": "NTP threshold",
    "NTP_THRESHOLD_EMPTY": "NTP threshold can't be empty",
    "SNMP_PORT": "SNMP port",
    "SNMP_PORT_EMPTY": "SNMP port can't be empty",
    "SNMP_THRESHOLD": "SNMP threshold",
    "SNMP_THRESHOLD_EMPTY": "SNMP threshold can't be empty",

    "PORT_RANGE": "Port range must be between 1 and 65535",
    "SAVE_FAIL": "Save cleandev configuration failed",
    "GET_FAIL": "Get cleandev configuration failed",
    "ADDR_EMPTY": "IP Address can't be empty",
    "INVALID_NUM":"Input must be numeral",
    "THRESHOLD_RANGE": "Threshold range must be between 1 and 9999999999",
    "EXISTED": "The cleandev is already existing"
},
"log": {
    "CLEAR_ALL":"Delete all",
    "LEVEL":"Level",
    "CONTENT":"Content",
    "TIME":"Time",
    "DEVIP":"Dev IP",
    "ID":"Id",
    "DOWNLOAD":"Download",
    "OPERATE":"Operate"
},
"protocol": {
    "TCP": "TCP",
    "UDP": "UDP",
    "ICMP": "ICMP",
    "OTHER": "Other"
},
"other": {
    "CONFIRM": "confirm delete?",
    "SELECT": "please select the items needed deleted",
    "BANNED": "forbid to delete the admin and the current user "
}
}
