{

"header" : {
  "navbar" : {
    "UPLOAD" : "上传",
    "new" : {
    	 "NEW" : "新建",
    	"PROJECT" : "项目",
    	"TASK" : "任务",
    	"USER" : "用户",
    	"EMAIL" : "E-Mail"
    },
    "NOTIFICATIONS" : "通知",
    "SETTING": "用户属性设置",
    "THEMESETTING": "主题设置",
    "HELP": "帮助",
    "LOGOUT": "注销"
  }
},

"product" : {
    "CORPORATION": "中国电子科技集团公司第三十二研究所(华东计算技术研究所)",
    "DATE" : "2015"
},

    "aside" : {
  "nav" : {
    "HEADER" : "导航栏",
    "DASHBOARD" : "平台概况",
    "ATTACK_ANALYSE" : "攻击分析",
    "FLOW_ANALYSE" : "流量分析",
    "CONFIGURATION" : "配置管理",
    "USER_MANAGEMENT" : "用户管理",
    "AUTH_MANAGEMENT" : "权限管理",
    "SYSTEM_CONFIG" : "系统设置",
    "CALENDAR" : "日历",
    "EMAIL" : "E-Mail",
    "WIDGETS" : "Widgets",
    "POLICY_MANAGEMENT" : "策略管理",
    "LOG" : "日志",
    "FLOW" : "流量",
    "components" : {
      "COMPONENTS" : "组件",
      "COMMON_COMPONENTS": "通用组件",
      "ui_kits" : {
    	"UI_KITS" : "UI控件",
    	 "BUTTONS" : "按钮",
    	 "ICONS" : "图标",
    	 "GRID" : "网格",
    	  "BOOTSTRAP" : "Bootstrap",
    	  "SORTABLE" : "排序",
    	  "PORTLET" : "Portlet",
    	  "TIMELINE" : "时间线",
    	  "VECTOR_MAP" : "向量表"
       },
      "FILE_UPLOAD": "文件上传",
      "FILE_DOWNLOAD": "文件下载",
      "DATEPICKER": "时间控件",
      "PROGRESSBAR": "进度条",      
      "table" : {
        "TABLE" : "表格",
        "TABLE_PAGE" : "表格与分页",
        "TABLE_STATIC" : "静态表格",
        "DATATABLE" : "数据表格",
        "FOOTABLE" : "表尾"
      },
      "form" : {
        "FORM" : "表单",
        "FORM_ELEMENTS" : "表单元素",
        "FORM_VALIDATION" : "表单验证",
        "FORM_WIZARD" : "表单对话框"
      },
      "CHART" : "图表",
      "pages" : {
        "PAGES" : "页",
        "PROFILE" : "用户属性",
        "POST" : "邮箱",
        "SEARCH" : "搜索",
        "INVOICE" : "通知",
        "LOCK_SCREEN" : "锁屏",
        "SIGNIN" : "登录",
        "SIGNUP" : "注册",
        "FORGOT_PASSWORD" : "忘记密码",
        "404" : "404"
      }
    },
    "your_stuff" : {
      "YOUR_STUFF": "Ihr Material",
      "PROFILE" : "Profil",
      "DOCUMENTS" : "文档"
    },
    "attackanalyse": {
        "ATTACK_TOTAL": "攻击概况",
        "ATTACK_LOCATION": "攻击源分布"
    },
    "flowanalyse": {
        "FLOW_TOTAL": "流量总览图",
        "FLOW_CONTRAST": "流量对比"
    },
    "policies": {
        "CONTROLLER":"检测设备",
        "NET_NODE": "网络节点",
        "PROTECT_OBJECT": "保护对象",
        "CLEAN_DEV":"清洗设备"
    },
    "systems": {
        "ADMINISTRATOR": "管理员配置",
        "BACKUP_RESTORE": "备份恢复"
    },
    "logs": {
        "SYSLOG": "系统日志",
        "OPLOG": "操作日志",
        "DEVLOG": "清洗日志"
    },
    "flows": {
        "HISTORY_FLOW": "历史流量",
        "FLOW_BASELINE": "流量基线"
    }
  },

  "MILESTONE" : "里程碑",
  "RELEASE" : "发布"
},
"settings": {
	"SETTINGS": "主题设置",
	"FIXED_HEADER": "固定页头",
	"FIXED_ASIDE": "固定侧边栏",
	"FOLDED_ASIDE": "折叠侧边栏",
	"DOCK_ASIDE": "Dock aside",
	"BOXED_LAYOUT": "Boxed layout",
	"RESET_SETTINGS": "恢复默认设置"
},
"usermanage": {
	"USERNAME": "用户名",
	"USERNAME_EMPTY": "用户名不能为空",
	"USERNAME_SAME": "该用户名已存在",
	"NICKNAME": "昵称",
	"NICKNAME_EMPTY": "昵称不能为空",
	"CREATETIME": "创建时间",
	"ROLES": "角色",
	"ROLE_EMPTY": "角色不能为空",
	"PASSWORD": "登陆密码",
	"RESETPW": "重置密码",
	"MODIFYPW": "修改密码",
	"NOMODIFYPW": "不修改",
	"NEWPASSWORD": "新密码",
	"CHECKPW": "确认密码",
    "CLEANDEV":"清洗设备"
},
"commonword": {
	"SAVE": "保存",
	"CANCEL": "取消",
	"DELETE": "删除",
	"BACK": "返回",
	"ADD": "添加",
	"LOADING": "加载中",
	"NODATA": "暂无数据",
	"EDIT": "编辑",
	"PASSWORDWRONG": "密码位数不能小于6位",
	"CHECKWRONG": "确认密码输入有误，请重新输入",
    "SAVE_FAIL": "保存数据失败",
    "GET_FAIL": "获取数据失败"
},
"overView": {
    "NORMAL": "速率正常次数",
        "EXCEPTION": "速率异常次数",
        "ATTACK": "攻击次数",
        "DEFENSE": "启动防御次数",
        "NUMBER_RATIO": "检测次数占比",
        "PROTOCOL_RATIO": "协议攻击占比",
        "ATTACK_EVENT": "最近攻击防御事件",
        "ATTACK_EVENT_ATTACKED": "遭受攻击",
        "ATTACK_EVENT_START_DEFENSE": "启动防御",
        "ATTACK_EVENT_STOP_DEFENSE": "停止防御",
        "START_LIMIT": "开始流量限速",
        "START_GUIDE": "开始引流",
        "STOP_LIMIT": "停止流量限速",
        "STOP_GUIDE": "停止引流",
        "NORMAL_TIME": "速率正常次数", 
        "ABNORMAL_TIME": "速率异常次数",
        "ATTACK_TIME": "攻击次数",
        "DETECT_TYPE": "检测类型",
        "EVENT_TYPE": "事件类型",
        "EVENT_TIME": "时间",
        "EVENT_PO": "对象",
        "EVENT_PROTOCOL": "协议",
        "EVENT_RATE": "攻击速率",
        "EVENT_DEFENSE": "防御措施",
        "ATTACK_DETAIL_LIST": "攻击详细列表",
        "RECOVER_NUMBER": "防御恢复次数"

},


"dataOverView": {
    "FLOW_CONTRAST":"流量对比",
    "INPUT_FLOW":"入流量",
    "OUTPUT_FLOW":"出流量",
    "ATTACK_FLOW":"攻击流量",
    "INPUT_FLOW_DISTRIBUTION":"入流量分布",
    "PROTOCOL_TCP":"TCP",
    "PROTOCOL_UDP":"UDP",
    "PROTOCOL_ICMP":"ICMP",
    "PROTOCOL_OTHER":"OTHER",
    "PROTECT_OBJECT_FLOW_TOP10":"保护对象流量Top 10",
    "IP_FLOW_TOP10":"攻击IP流量Top 10",
    "TIME":"时间",
    "TRAFFIC":"流量(B/s)",
    "PO":"保护对象",
    "IP":"IP"
},

"attackView":{
    "ATTACK_NUM": "攻击次数",
    "DEFENSE_NUM": "启动防御次数",
    "CLEAN_TRAFFIC":"清洗流量",
    "ATTACK_SRC_NUM":"攻击源总数",
    "DDOS_ATTACK_TYPE":"DDOS攻击类型分布",
    "CC_ATTACK":"CC",
    "SYN_FLOOD":"SYN FLOOD",
    "ACK_FLOOD":"ACK FLOOD",
    "SYN_ACK_FLOOD":"SYN-ACK FLOOD",
    "FIN_RST_FLOOD":"FIN-RST FLOOD",
    "UDP_FLOOD":"UDP FLOOD",
    "ICMP_FLOOD":"ICMP FLOOD",
    "DNS_FLOOD":"DNS FLOOD",
    "ATTACK_DETAIL":"攻击详情列表",
    "PO_IP":"保护对象IP地址",
    "PO_NAME":"保护对象名称",
    "ABNORMAL_STARTING_TIME":"异常开始时间",
    "ATTACK_STARTING_TIME":"攻击开始时间",
    "END_TIME":"结束时间",
    "DURATION_TIME":"持续时间",
    "STATUS":"攻击状态",
    "TYPE":"攻击类型",
    "ATTACK_TYPE":"攻击类型",
    "ATTACK_SRC_IP":"攻击源IP",
    "ATTACK_PKT_NUM":"攻击报文数",
    "ATTACK_BYTES_NUM":"攻击字节数",
    "ATTACK_FLOW_VALUE":"攻击流量值",
    "ATTACK_PEAK":"攻击峰值",
    "FLOW_THRESHOLD":"阀值",
    "DDOS_DEFENSE_WEEK_TREND":"DDOS防御周趋势图",
    "DDOS_DEFENSE_24HOURS_TREND":"DDOS防御24小时趋势图",
    "DDOS_DEFENSE_NUM":"DDOS防御次数",
    "MAX_ATTACK_FLOW":"最大攻击流量(GB/s)"
},

"flowDisplay": {
    "SELECT_PO":"请选择保护对象",
    "SELECT_PROTOCOL":"请选择协议",
    "SELECT_TIME":"请选择流量显示时间段",
    "FLOWTIME":"时间",
    "INPUT":"入流量(B/s)",
    "OUTPUT":"出流量(B/s)",
    "ATTACK":"攻击流量(B/s)",
    "QUERY":"查询",
    "DISPLAYSHOW":"流量展示图",
    "HOUR_CHART":"一小时流量图",
    "WEEK_CHART":"一周流量图",
    "DAY_CHART":"一天流量图",
    "MONTH_CHART":"月流量图",
    "YEAR_CHART":"年流量图",
    "BASELINE_CHART":"流量基线图",
    "RROTOCOL_DIST":"协议分布图",
    "RROTOCOL":"协议",
    "RATE":"速率(B/s)",
    "PERCENT":"百分比",
     "BASELINE_SPEED" : "基线值速率",
     "BASELINE_LEARNING" : "基线学习中，暂无基线值",
     "ONE_HOUR" : "1小时",
     "ONE_DAY" : "1天",
     "ONE_WEEK" : "1周",
     "ONE_MONTH" : "1月",
     "ONE_YEAR" : "1年",
     "FLOW_CHART" : "流量图",
     "SPEED" : "速率",
     "TIME" : "时间",
     "HOUR" : "时",
     "MON" : "星期一",
     "TUE" : "星期二",
     "WED" : "星期三",
     "THURS" : "星期四",
     "FRI" : "星期五",
     "SAT" : "星期六",
     "SUN" : "星期日"

},

"controller": {
    "TYPE": "控制器类型",
    "HOST": "检测设备地址",
    "PORT": "端口",
    "USER": "用户名",
    "PASSWORD": "密码",
    "INTERVAL": "检测时间间隔（秒）",
    "EXCEPTION_COUNT": "异常次数阀值",
    "EXCEPTION_PER": "异常流量百分比",
    "RECOVER_COUNT": "攻击恢复次数阀值",
    "SAVE_FAIL": "保存检测设备配置失败",
    "GET_FAIL": "获取检测设备配置失败",
    "ADDR_EMPTY": "地址不能为空",
    "EXISTED": "该检测设备信息已存在",
    "PORT_EMPTY": "端口不能为空",
    "PORT_RANGE": "端口范围必须在1-65535之间",
    "USER_EMPTY": "用户名不能为空",
    "PASSWORD_EMPTY": "密码不能为空",
    "TIME_INTERVAL_EMPTY": "间隔时间不能为空",
    "TIME_INTERVAL_RANGE": "间隔时间必须在5-600之间",
    "EXCEPTION_COUNT_EMPTY": "异常次数阀值不能为空",
    "EXCEPTION_COUNT_RANGE": "异常次数阀值必须在0-100之间",
    "EXCEPTION_PER_EMPTY": "异常流量偏差百分比不能为空",
    "EXCEPTION_PER_RANGE": "异常流量偏差百分比必须在0-1000之间",
    "RECOVER_COUNT_EMPTY": "攻击恢复次数阀值不能为空",
    "RECOVER_COUNT_RANGE": "攻击恢复次数阀值必须在0-100之间"
},
"netnode": {
    "NAME": "交换机名称",
    "ID": "交换机ID",
    "CONTROLLER_ID": "控制器ID",
    "NAME_EXIST": "该交换机信息已存在",
    "NAME_EMPTY": "名称不能为空",
    "ID_EMPTY": "交换机Id不能为空",
    "SAVE_FAIL": "保存网络节点信息失败",
    "GET_FAIL": "获取网络节点信息失败"
},
"backup": {
    "BACKUPDB": "备份",
    "BACKUPANDDOWNLOAD": "下载配置",
    "SELECTBACKUPFILE": "恢复",
    "SELECTFILE": "选择文件",
    "UPLOADRESTORE": "恢复",
    "GET_FAIL": "获取配置信息失败",
    "BACKUPSUCCESS": "备份配置信息成功！",
    "BACKUPFAIL": "备份配置信息失败！",
    "RESTORESUCCESS": "恢复配置信息成功！",
    "RESTOREFAIL": "恢复配置信息失败！"
},
"po": {
    "NAME": "名称",
    "CONNECT_MODE":"连接模式",
    "BYPASS_MODE":"旁路模式",
    "TADEM_MODE":"串联模式",
    "CLEAN_DEV": "清洗设备",
     "IFACE_PORT": "清洗端口",
    "EXIST_DETECTOR": "存在检测设备",
    "NAME_EXIST": "该保护网络名称已存在",
    "NAME_EMPTY": "名称不能为空",
    "INPUT_PORT": "外网接口",
    "INPUT_PORT_EMPTY": "外网接口不能为空",
    "OUTPUT_PORT": "内网接口",
    "OUTPUT_PORT_EMPTY": "内网接口不能为空",
    "CLEANDEV_OUTPORT": "清洗设备输出端口",
    "CLEANDEV_INPORT": "清洗设备输入端口",
    "PROTECT_NETWORK": "保护网络",
    "PROTECT_NETWORK_EMPTY": "保护网络输入不正确，格式为:10.10.10.10/32",
    "NETWORK_EXIST": "保护网络已经存在",
    "PROTECT_NETWORK_NULL": "保护网络不能为空",
    "DEFENSE_TYPE": "防御类型",
    "DEFENSE_TYPE_EMPTY": "防御类型不能为空",
    "GUIDE_PORT": "引流接口",
    "GUIDE_PORT_EMPTY": "引流接口不能为空",
    "REINJECTION_PORT": "回注接口",
    "REINJECTION_PORT_EMPTY": "回注接口不能为空",
    "CONNECT_SWITCH": "所属检测设备",
    "CONNECT_CLEANDEV": "所属清洗设备",
    "TENANT": "选择租户",
    "SHOW_TENANT": "所属租户",
    "SELECT_TENANT":"请选择租户",
    "CONNECT_SWITCH_EMPTY": "所属检测设备不能为空",
    "PROTOCOL": "协议",
    "PROTOCOL_EMPTY": "请至少选择一种协议类型",
    "FLOW_THRESHOLD": "设置流量阀值",
    "AUTO_LEARN": "自动学习流量阀值",
    "FIXED_FLOW_THRESHOLD": "固定流量阀值",
    "FLOW_THRESHOLD_TYPE_EMPTY": "流量阀值类型不能为空",
    "THRESHOLD_RANGE": "阀值范围必须在1-999999999之间",
    "IPOPTION_THRESHOLD": "IP Option阀值",
    "IPOPTION_THRESHOLD_EMPTY": "IP Option阀值不能为空",
    "ICMP_REDIRECT":"ICMP重定向",
    "PPS_EMPTY": "pps不能为空",
    "KBPS_EMPTY": "KB/s不能为空",
    "PPS_TYPE": "pps必须为正整数",
    "KBPS_TYPE": "KB/s必须为正整数",
    "SAVE_FAIL": "保存PO信息失败",
    "GET_FAIL": "获取PO信息失败"
},
"cleandev": {
    "CLEANDEV_IP": "清洗设备IP",
    "CLEAN_DIRECTION": "清洗方向",
    "CLEAN_DIRECTION_EMPTY": "清洗方向不能为空",
    "UNIDERECTION": "单向清洗",
    "BIDIRECTIONAL": "双向清洗",
    "TCP_FIRST_SYN":"TCP首包丢弃",
    "CHECK_INTERVAL": "检测周期",
    "CHECK_INTERVAL_EMPTY": "检测周期不能为空",
    "TCP_FLOOD_THRESHOLD": "TCP洪水阀值",
    "TCP_FLOOD_THRESHOLD_EMPTY": "TCP洪水阀值不能为空",
    "TCP_SYN_CLEAN": "TCP SYN阀值",
    "TCP_SYN_CLEAN_EMPTY": "TCP Syn阀值不能为空",
    "TCP_SYNACK_CLEAN": "TCP syn+ack阀值",
    "TCP_SYNACK_CLEAN_EMPTY": "TCP syn+ack阀值不能为空",
    "TCP_ABNORMAL_CLEAN": "TCP异常报文清洗",
    "TCP_ABNORMAL_CLEAN_EMPTY": "TCP异常报文清洗不能为空",
    "UDP_THRESHOLD": "UDP洪水阀值",
    "UDP_THRESHOLD_EMPTY": "UDP洪水阀值不能为空",
    "ICMP_THRESHOLD": "ICMP洪水阀值",
    "ICMP_THRESHOLD_EMPTY": "ICMP洪水阀值不能为空",
    "ICMP_ABNORMAL_CLEAN": "ICMP异常报文清洗",
    "ICMP_ABNORMAL_CLEAN_EMPTY": "ICMP异常报文清洗不能为空",
    "HTTP_THRESHOLD": "HTTP洪水阀值",
    "HTTP_THRESHOLD_EMPTY": "HTTP洪水阀值不能为空",
    "HTTP_REQUEST_THRESHOLD": "Http request阀值",
    "HTTP_REQUEST_THRESHOLD_EMPTY": "Http request阀值不能为空",
    "HTTP_HEADER_THRESHOLD": "HTTP header慢速攻击阀值",
    "HTTP_HEADER_THRESHOLD_EMPTY": "HTTP header慢速攻击阀值不能为空",
    "HTTP_POST_THRESHOLD": "HTTP post阀值",
    "HTTP_POST_THRESHOLD_EMPTY": "HTTP post阀值不能为空",
    "HTTP_PORT": "Http端口",
    "HTTP_PORT_EMPTY": "Http端口不能为空",
    "HTTP_SRC_AUTH":"Http源认证",
    "HTTPS_FLOOD_THRESHOLD": "HTTPS洪水阀值",
    "HTTPS_FLOOD_THRESHOLD_EMPTY": "HTTPS洪水阀值不能为空",
    "HTTPS_REQUEST_THRESHOLD": "Https request阀值",
    "HTTPS_REQUEST_THRESHOLD_EMPTY": "Https request阀值不能为空",
    "HTTPS_THC_THRESHOLD": "HTTPS thc阀值",
    "HTTPS_THC_THRESHOLD_EMPTY": "HTTPS thc阀值不能为空",
    "HTTPS_PORT": "Https端口",
    "HTTPS_PORT_EMPTY": "Https端口不能为空",
    "DNS_REQ_THRESHOLD": "DNS request阀值",
    "DNS_REQ_THRESHOLD_EMPTY": "DNS request阀值不能为空",
    "DNS_REP_THRESHOLD": "DNS reply阀值",
    "DNS_REP_THRESHOLD_EMPTY": "DNS reply阀值不能为空",
    "DNS_PORT": "DNS端口",
    "DNS_PORT_EMPTY": "DNS端口不能为空",
    "DNS_ABNORMAL_CLEAN": "DNS异常报文清洗",
    "DNS_ABNORMAL_CLEAN_EMPTY": "DNS异常报文清洗不能为空",

    "NTP_PORT": "NTP端口",
    "NTP_PORT_EMPTY": "NTP端口不能为空",
    "NTP_THRESHOLD": "NTP阀值",
    "NTP_THRESHOLD_EMPTY": "NTP阀值不能为空",
    "SNMP_PORT": "SNMP端口",
    "SNMP_PORT_EMPTY": "SNMP端口不能为空",
    "SNMP_THRESHOLD": "SNMP阀值",
    "SNMP_THRESHOLD_EMPTY": "SNMP阀值不能为空",

    "PORT_RANGE": "端口范围必须在1-65535之间",
    "SAVE_FAIL": "保存清洗设备配置失败",
    "GET_FAIL": "获取清洗设备配置失败",
    "ADDR_EMPTY": "IP地址不能为空",
    "INVALID_NUM":"请输入有效数字",
    "THRESHOLD_RANGE": "阀值范围必须在1-999999999之间",
    "EXISTED": "该清洗设备信息已存在"
},
"log": {
    "CLEAR_ALL":"清空日志",
    "LEVEL":"级别",
    "CONTENT":"内容",
    "TIME":"时间",
    "DEVIP":"设备地址",
    "ID":"ID",
    "DOWNLOAD":"下载日志",
    "OPERATE":"操作"
},
"protocol": {
    "TCP": "TCP",
    "UDP": "UDP",
    "ICMP": "ICMP",
    "OTHER": "其它"
},
"other": {
    "CONFIRM": "确定删除?",
    "SELECT": "请选择删除项",
    "BANNED": "禁止删除admin用户和当前用户"
}
}
